### ISSUE TITLE
Too many return values error on loadController()

### ISSUE THREAD

**Issue by joesamcoke** [livebud/bud#101]
Hi, Firstly this project looks great. Really looking forward to working with it.

Getting the error...

bud/.app/controller/controller.go:133:15: too many return values
        have (nil, error)

Looks the loadController() is missing a return error definination

`func loadController() *controller.Controller {
	controllerController, err := controller.Load()
	if err != nil {
		return nil, err
	}
	return controllerController
}`

**Comment by matthewmueller** [comment]
Hey @joesamcoke, thanks for giving bud a try! Can you share what you wrote in your controller/ directory?

**Comment by joesamcoke** [comment]
eek, ok that's done

**Comment by matthewmueller** [comment]
Ah interesting, let me try to reproduce this!

**Comment by matthewmueller** [comment]
Yep, confirmed the issue. I'll get this fixed!

**Comment by Pubg887** [comment]
Jj

**Comment by matthewmueller** [comment]
Accident?
