### ISSUE TITLE
Unexpected `fmt.Println` behavior on non-change hot reloads

### ISSUE THREAD

**Issue by 012e** [livebud/bud#129]
### Reproduce
1. Create a project normally
2. Create any route `bud new controller hello:/ index`
3. Add `fmt.Println("anything")` in the controller
```go
func (c *Controller) Index(ctx context.Context) (hellos []*Hello, err error) {
	fmt.Println("Hello world")
	return []*Hello{}, nil
}
```
4. `bud run`
Every time I save my controller.go file, no `Hello world` message is printed.
5. Go to http://127.0.0.1:3000
We will see `Hello world` message prompted in the terminal. **Don't change anything** and save one/multiple times controller.go, `Hello world`s will be printed out (it's **inconsistent**, sometime nothing is printed out)

**Comment by matthewmueller** [comment]
Thanks for opening this @012e, I just tested it. I don't think it's a bug. Here's what's happening:

> 4. bud run
Every time I save my controller.go file, no Hello world message is printed.

There are no requests being made to `/`, so the controller is not running and no `fmt.Println` is being printed out.

> Go to http://127.0.0.1:3000/
We will see Hello world message prompted in the terminal. Don't change anything and save one/multiple times controller.go, Hello worlds will be printed out (it's inconsistent, sometime nothing is printed out)

When you hit save and you have a live reload connection established to a browser window, live reload will rebuild the app and refresh the page. When the page is refreshed that new request hits the controller.

You can fix this by closing your browser window. If you had more browser windows open, you'd have more lines printed to stdout.

Ah, thTis isn't a bug
