### ISSUE TITLE
View receiving empty objects

### ISSUE THREAD

**Issue by donovanrost** [livebud/bud#134]
I have made a new controller user `bud new controller users index show`. This scaffolded the controller and view as expected.
I then modified the controller to :
```package users

import (
	context "context"
)

type Controller struct {
	// Dependencies...
}

// User struct
type User struct {
	id        int
	firstName string
	lastName  string
}

// Index of users
// GET /users
func (c *Controller) Index(ctx context.Context) (users []*User, err error) {

	var u1 = User{1, "firstname", "lastname"}
	users = append(users, &u1)
	return users, err

}

// Show user
// GET /users/:id
func (c *Controller) Show(ctx context.Context, id int) (user *User, err error) {
	return &User{}, nil
}
```

When I go to `http://127.0.0.1:3000/users`, I only see the scaffolded header "User Index". Unsure of what what happening, since the table wasn't displayed, I added another header:
`<h1>{JSON.stringify(users)}</h1>`  to inspect the content of the `users` variable inside of `index.svelte`

This displays with
> [{}]

This suggests that an object is being serialized, but the contents of the objects are being discarded somewhere. 

Am I doing something wrong?

**Comment by 012e** [comment]
You forgot to export your struct fields 👀

**Comment by donovanrost** [comment]
@012e thank you! I'm learning Go on the fly. I really appreciate your help

**Comment by matthewmueller** [comment]
Yah, I suppose this might not be obvious. I took a note to add something in the docs.
