### ISSUE TITLE
Support .svelte files in node_modules

### ISSUE THREAD

**Issue by matthewmueller** [livebud/bud#187]
This issue has come up twice so far where folks are trying to include `.svelte` files from `node_modules`:

1. https://github.com/livebud/bud/discussions/99
2. Trying to use svelte-time in [Bass Loop](https://github.com/vito/bass-loop/blob/d162db218c056964e1c77e92a72d458e9d69579d/view/RunSummary.svelte#L2)

Honestly, I thought this was considered a bad practice™️ and that authors should pre-compiled their files to JS before publishing to NPM. You may recall the Babel days where NPM packages often required a certain flavor of Babel configuration. 

After seeing this pop up twice now, I had a peak at other Svelte components and it appears that it's a common practice in the Svelte community:

- https://github.com/metonym/svelte-time/blob/master/src/Time.svelte
- https://github.com/romkor/svelte-portal/tree/master/src
- https://github.com/ValentinH/svelte-easy-crop/blob/master/src/index.svelte

Maybe because there isn't a compiled JS format that can be imported and treated as a Svelte file by another Svelte file. Anyways, what this means is that Bud should support importing `.svelte` files from within `node_modules`.

**Comment by jfmario** [comment]
I can do this now with bud as it is (at least as of the latest main branch).

```svelte
import Time from 'svelte-time';
import DataTable, { Head, Body, Row, Cell } from '@smui/data-table';
```

This worked with no issue for me during `bud run`.

**Comment by matthewmueller** [comment]
Ah interesting! I don't think I touched this code, so I'd be surprised if something changed. Do you mind prepping a small example?

**Comment by jfmario** [comment]
I made a test case that demonstrates it in `framework/view/view_test.go`.

`go test ./framework/view`

**Comment by matthewmueller** [comment]
This seems to be possible after testing it in #221. We can re-open if we discover it's more nuanced. Thanks @jfmario!
