### ISSUE TITLE
bud  create app  fail

### ISSUE THREAD

**Issue by Jeffrey-mu** [livebud/bud#204]
run create bud_app

| create: Unable to infer a module name. Try again using the module <path> name.

For example,
        bud create --module=github.com/my/app bud_app
![image](https://user-images.githubusercontent.com/66287770/179136031-0891bf62-a299-4f77-9eed-caed4ee4ccbb.png)

**Comment by matthewmueller** [comment]
Hey @Jeffrey-mu, I just tried: `bud create --module=github.com/my/app bud_app` and it worked for me. What error did you see?

Also, how did you hear about Bud? 👀  I'm seeing an influx of stars but I can't find the link.

**Comment by Jeffrey-mu** [comment]
@matthewmueller 
Thank you very much. I may have failed due to network problems before. I'll try again

**Comment by matthewmueller** [comment]
Oh yes, there's an NPM install in there. That will go away soon.

**Comment by Jeffrey-mu** [comment]
@matthewmueller 
ok It's all right now. It's the agent's problem
Terminal input
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.io,direct
Thank you, brother😃

**Comment by matthewmueller** [comment]
Yo @Jeffrey-mu, how'd you hear about Bud? Please share a link 🙏

**Comment by Jeffrey-mu** [comment]
@

**Comment by Jeffrey-mu** [comment]
is ok

**Comment by matthewmueller** [comment]
Cheers, thanks man!
