### ISSUE TITLE
`make install` requires github.com/pointlander/peg

### ISSUE THREAD

**Issue by jmmk** [livebud/bud#215]
Following https://github.com/livebud/bud/blob/main/contributing/Readme.md#setting-up-bud-for-development, `make install` fails on the `go generate` step unless https://github.com/pointlander/peg is available on `PATH`.

Using `go install github.com/pointlander/peg` worked to install it.

**Comment by matthewmueller** [comment]
Thanks for your interest in contributing to Bud! I just pushed up a fix.
