### ISSUE TITLE
`bud create --dev` fails when there is a space in the file path

### ISSUE THREAD

**Issue by jmmk** [livebud/bud#216]
Running `create` on a directory like `/tmp/space dir` causes an issue with `go mod`

```
/tmp/space dir $ bud create --module=test --dev .
go: errors parsing go.mod:
/tmp/space dir/go.mod:10:2: malformed module path "/tmp/space": empty path element
| exit status 1
```

If we check the `go.mod` file contents, we see it was templated without quotes and is being interpreted as `/tmp/space`

```
/tmp/space dir $ cat go.mod
module test

go 1.18

require (
	github.com/livebud/bud v0.2.1
)

replace (
	github.com/livebud/bud => /tmp/space dir
)
```

If we remove the `replace` directive and try with `go mod edit`, we can see what the quoted version looks like:

```
/tmp/space dir $ cat go.mod
module test

go 1.18

require github.com/livebud/bud v0.2.1
/tmp/space dir $ go mod edit -replace github.com/livebud/bud="$PWD"
/tmp/space dir $ cat go.mod
module test

go 1.18

require github.com/livebud/bud v0.2.1

replace github.com/livebud/bud => "/tmp/space dir"
```

---

It's possible that other characters will cause issues as well, but I only noticed/tested with a space.

The fix might be as simple as always quoting the directory, i.e. using `"{{ $rep.To }}"` in https://github.com/livebud/bud/blob/main/internal/cli/create/gomod.gotext. It looks like `go mod tidy` will automatically remove the quotes if they are not needed. 

https://github.com/golang/mod/blob/86c51ed26bb44749b7d60a57bab0e7524656fe8a/modfile/rule.go#L672 is responsible for the quoting behavior

Alternatively, you could probably use `go mod` commands (either shelling out or by including golang.org/x/mod as a library) to generate the file instead of using a template

**Comment by matthewmueller** [comment]
Hey @jmmk, I just tested it on my machine and while I wasn't able to reproduce your error:

```
/tmp/space dir/go.mod:10:2: malformed module path "/tmp/space": empty path element
```

I did test `go mod edit -replace github.com/livebud/bud="$PWD"` with a spaces in `$PWD` and it auto-quoted. 

And thanks for pointing me to `modfile.AutoQuote`! I just added it in.

**Comment by jmmk** [comment]
I tested your branch and it seems to work fine.

It seems unlikely that a go module name would need to be quoted, but in the module code they do use AutoQuote on every value (module name, `require`s, `replace`s), so it could be worth considering using it on those as well.
