### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by josebalius** [livebud/bud#23]
Watched the demo and it was pretty good!

I am curious if you've thought about adding a way of rendering the views server-side instead of using Svelte? For example, using Go's templating system. I realize you lose out on the component capabilities of today's FE frameworks, but as someone who prefers server-side rendered apps, I think this would be a good feature to support. As mentioned it can be another variation that bud supports in addition to svelte, React and others.

**Comment by matthewmueller** [comment]
Hey @josebalius, thanks opening this issue. [SSR rendering works out of the box](https://github.com/livebud/bud/tree/main/runtime/view/ssr) already! 

This was hard to do, but I couldn't live with the tradeoff of choosing between a modern FE frontend and performance, SEO, web standards.

I should have shown it in the demo, but if you go through the HN demo, try running `curl :3000` and you'll be overwhelmed with HTML soup!
