### ISSUE TITLE
Hosting bud app in Heroku?

### ISSUE THREAD

**Issue by Bishwas-py** [livebud/bud#241]
I tried hosting Bud in Herko, [this app](https://github.com/Bishwas-py/bud-example), but got failed 'cause `bud/app` was just a symlink, not an executable. 

Here's my procfile...

```
web: bud/app
```
Yeah, I know that bud/app must have its symlink to work but I was unable to do so. How can I host it well in Heroku? I was quite able to do it in my AWS vps, but just wanna do it in Heroku for now...

**Comment by McGeerDev** [comment]
Hey man how did try hosting your app? What steps did you follow? Did you get any errors? Looking forward to learning with you.

**Comment by Bishwas-py** [comment]
> @McGeerDev Hey man how did try hosting your app? What steps did you follow? Did you get any errors? Looking forward to learning with you.

Just pushing the coding through `git push heroku main`

Getting this message...

```
remote: -----> Using go1.18.3
remote: -----> Determining packages to install
remote: -----> Running: go install -v -tags heroku ./cmd/... 
remote: go: warning: "./cmd/..." matched no packages
remote:        
remote:        Installed the following binaries:
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 430.1K
remote: -----> Launching...
remote:        Released v7
```

**Comment by matthewmueller** [comment]
Hey @Bishwas-py, thanks for experimenting with this. This is definitely an area that needs some research and improvement. 

`bud build` should provide you a non-symlink executable. I'll start looking into this in a few weeks once I'm looking to deploy the website.

In the meantime, let us know if you figure it out! I'm here to help if you explore further!
