### ISSUE TITLE
bud create hello error

### ISSUE THREAD

**Issue by pikooli** [livebud/bud#266]
Hello when I try bud I got this error.

     ~ bud create hello
     | create: Unable to infer a module name. Try again using the module <path> name.

     For example,
     bud create --module=github.com/my/app hello

My version : 

    ~ bud version
         bud: 0.2.3
      svelte: 3.47.0
      react: 18.0.0

**Comment by matthewmueller** [comment]
Hey @pikooli, does `bud create --module=github.com/my/app hello` also not work for you?

**Comment by verrol** [comment]
I got the same error and it works with `--module`, but the docs needs to be updated.

**Comment by matthewmueller** [comment]
Closing since the PR that improves this is already merged into main: https://github.com/livebud/bud/pull/242

And we'll get a new release out soon!
