### ISSUE TITLE
Question: How is bud different than using Go-templates?

### ISSUE THREAD

**Issue by spy16** [livebud/bud#290]
I have been struggling to find an easy-to-use fullstack setup that allows me to quickly build full-fledged apps in my indie-hacking journey.. This looks like the perfect tool (I tried the hacker-news tutorial and i am sold!!). ❤️

But I don't fully understand how this works. It looked like everything was being done server-side. What is the difference between this and using Go templates? 🤔 Is there some hydration mechanism built into this?

**Comment by matthewmueller** [comment]
Hey @spy16, I wrote that up in this discussion: https://github.com/livebud/bud/discussions/248. Have a look and let me know if you have any questions in there.
