### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by febriliankr** [livebud/bud#32]
I was doing install script in my macbook air m1
`$ curl -sf curl https://raw.githubusercontent.com/livebud/bud/main/install.sh | sh`

then I got this error
`livebud/bud: platform darwin/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/livebud/bud/issues/new`

**Comment by matthewmueller** [comment]
Thanks for opening this issue, I just released [v0.1.0](https://github.com/livebud/bud/releases/tag/v0.1.0) which hopefully should address this.

Unfortunately I wasn't able to test this myself, so please give it a go. Let me know.
