### ISSUE TITLE
Issue with afs on bud run

### ISSUE THREAD

**Issue by oceanbornphoenix** [livebud/bud#408]
Created new bud application following readme instructions. But when I attempt to run with "bud run" it gives the following error.

change.me/bud/internal/generator
| genfs: open "bud/cmd/afs/main.go". framework/afs: unable to load state afs: afs: unable to wire. di: unable to wire "change.me/bud/cmd/afs".loadGeneratorFS function. di: unable to find definition for param "github.com/livebud/bud/package/genfs".*FileSystem in "github.com/livebud/bud/package/genfs".FS. %!w(<nil>)

Not really sure what to do to fix it. The instructions didn't mention requiring any external dependencies. Only thing I can think of is that I'm running on arch linux. I also tried in an ubuntu vm with the same result.

**Comment by oceanbornphoenix** [comment]
I'm an idiot. When I first ran bud I hadn't had go installed yet. For some reason I thought it would install as part of the process. I installed it and recreated the project and it works.

**Comment by Dwiga** [comment]
Hi, I am using golang inside asdf, and having same issue as yours... is bud not support asdf just yet?
