### ISSUE TITLE
Add support for skeleton UI

### ISSUE THREAD

**Issue by henrriusdev** [livebud/bud#409]
Many Svelte developers (including me) use **UI libraries** that already have several components to save us time, however, Bud currently does not support one of these libraries, specifically [skeleton.dev](https://skeleton.dev), for the tailwind part, there is no problem, it could be included by cdn, but when using this script in any of the views, it generates an error

```svelte
<script lang="ts">
  import "@skeletonlabs/skeleton/themes/theme-skeleton.css"
  import "@skeletonlabs/skeleton/styles/skeleton.css"
</script>
<!-- Tailwind script cdn -->
```

Error received: `view: render error error="genfs: open \"bud/view/_ssr.js". expected exactly 1 output file but got 2"`

I guess a modification would have to be made to allow additional stylesheets to be added. To contribute to this project, I will try other similar libraries to see if there are no problems when using them.

**Comment by Bishwas-py** [comment]
It might be the issue of Svelte version, livebud supporting `3.47.0` and skeletonlabs with a Svelte for of `4.2.0`.
