### ISSUE TITLE
Provide a nicer error message for unsupported Go versions

### ISSUE THREAD

**Issue by one-aalam** [livebud/bud#45]
After creating a fresh project, the command `bud run` fails with import related errors 
<img width="851" alt="bud-h" src="https://user-images.githubusercontent.com/532906/168464730-c89625c4-95c2-4fb6-858e-c6df6f3b48aa.png">

Looks like the scaffolded structure is missing some important directories/files, but I'm not sure why that's happening
<img width="846" alt="bud-h" src="https://user-images.githubusercontent.com/532906/168464840-3f820fd0-84c3-4263-8aaa-d79ccd95e6c0.png">

**Comment by matthewmueller** [comment]
Oh, interesting! I guess you're running a version of Go that's less than 1.16? Bud relies heavily on `io/fs` and will take advantage of generics in the future, so I suggest running Go 1.18+ if you can.

That's an awful error nonetheless, I'll improve that. Let me know what version you're running with `go version`.

**Comment by one-aalam** [comment]
Hey @matthewmueller Thank you. Bud's running flawlessly with the `golang` upgrade.

**Comment by joshuatalb** [comment]
I was also caught out by this. I've made a small PR (#53) to add a comment in the `README.md` about this.

**Comment by jmaister** [comment]
It could help that the `cli` checks for the appropriate version of go and exit with a nice message.

Maybe when running on Windows, I also read in other issues that there are problems with it too.

**Comment by matthewmueller** [comment]
Agreed. Accepting PRs!
