### ISSUE TITLE
Include version in released tarball filename to support package managers like AUR

### ISSUE THREAD

**Issue by cloudlena** [livebud/bud#52]
It would be great to have this repo in the [AUR](https://aur.archlinux.org/) as `bud-bin`. I'm happy to publish it there and maintain it. Or would you prefer to do it yourself?

**Comment by matthewmueller** [comment]
@cloudlena thanks for the issue. I'd appreciate if you could publish and maintain it. I know next to nothing about Arch Linux other than being happy when it's the base image in a Dockerfile. 

One thing, I'll be changing `curl -sf https://raw.githubusercontent.com/livebud/bud/main/install.sh | sh` to `curl -sf livebud.com/install | sh` pretty soon.

Are AUR packages hosted on Github? I'm assuming I could open a PR?

**Comment by cloudlena** [comment]
Thanks, @matthewmueller. It's already done: https://aur.archlinux.org/packages/bud-bin

Please let me know if I should change anything about how it's set up.

**Comment by matthewmueller** [comment]
Excellent, thank you @cloudlena!

**Comment by cloudlena** [comment]
@matthewmueller, with version `0.1.3` released, I'm having problems with the checksum. I think it's because the package manager doesn't recognize the downloaded as tarball as a new version. Can we include the version numbers in the binaries released in "Assets" here: https://github.com/livebud/bud/releases?

So, for example, call the file `bud_v0.1.3_linux_amd64.tar.gz` instead of `bud_linux_amd64.tar.gz`

**Comment by matthewmueller** [comment]
Ah interesting, yes that's totally doable. I actually explicitly removed the versions because it felt redundant with the release version. For example,

```
https://github.com/livebud/bud/releases/download/v0.1.3/bud_v0.1.3_darwin_amd64.tar.gz
```

I'll add it back in. This will break old installations, but I think that's okay for the early days.
