### ISSUE TITLE
Support other Actions

### ISSUE THREAD

**Issue by theEyeD** [livebud/bud#54]
Based on the docs:
![image](https://user-images.githubusercontent.com/4244606/168490884-17d7b0ae-7588-483d-bf7e-80876665b101.png)

When adding other actions currently it results in a 404.

**Comment by theEyeD** [comment]
It looks like it's already attempting to add the route but failing due to uppercase letters being in the route. Forcing the route to lowercase before passing it to `lex.New` resolves the issue:
https://github.com/livebud/bud/blob/c64854dcaaeec778c713eea979a5be13a737ad56/package/router/radix/tree.go#L78

There could also probably be changes made within `lex` to handle it. Let me know if you have a preference or other ideas and I can get a PR created.

**Comment by theEyeD** [comment]
Just as a side note, keeping the custom (more specific) routes at the top can help prevent conflicting routes. I ran into an issue when having:
```go
func (c *Controller) Show(id int) {

}

func (c *Controller) Test(str string) string {
	return str
}
```
Calling `/test?str=123` resulted in it attempting to route to `Show` and returning:
```json
{"error":"could not parse int from \"test\""}
```

However, switching the order of the funcs resulting in both `/test?str=123` and `/123` to work as expected.

**Comment by matthewmueller** [comment]
> It looks like it's already attempting to add the route but failing due to uppercase letters being in the route.

Oh cool. I think I'd prefer lowercasing in the generator's state and keeping the lexer more strict.

> keeping the custom (more specific) routes at the top can help prevent conflicting routes.

Oh good point , I thought the router was already ready for that though. For example `/test` has priority over `/:id`. Is that not the case?
