### ISSUE TITLE
Add bud new controller <resource> {create,new,edit,update,delete} actions

### ISSUE THREAD

**Issue by TechplexEngineer** [livebud/bud#55]
Thanks for making bud!

I must be doing something wrong here. I'd like to scaffold create, read, update and delete actions. 

It seems like only index and show are implemented, is that correct? (when running `bud new controller ...`

**Comment by matthewmueller** [comment]
@TechplexEngineer thanks for checking out Bud. You're not doing something wrong!

This is slightly embarrassing, but scaffolding was the last thing I wrote and I was so over keeping bud a secret at that point, that I implemented the bare minimum to record the demo.

Sincere apology for the confusion, I meant to fix this up before anyone noticed.

**Comment by matthewmueller** [comment]
The PR has been started in #75
