### ISSUE TITLE
Add M1 binary support

### ISSUE THREAD

**Issue by matthewmueller** [livebud/bud#6]
Need to make this happen! Two requests so far from @kuldar and @sid405 😊 

From Sidd:
> I was able to get Bud running under Rosetta 2 by starting a Rosetta2 shell: `arch -arch x86_64 zsh`. I have this aliased to `rosetta` because I need it every once in a while.

**Comment by matthewmueller** [comment]
This **might** be working now. Please try again:

```sh
curl -sf curl https://raw.githubusercontent.com/livebud/bud/main/install.sh | sh
```

I wasn't able to test this since I'm not on an M1. I did see some V8 warnings, but no errors. Let's see 😅

**Comment by sid405** [comment]
Can confirm that this runs just fine without errors now!
