### ISSUE TITLE
Proper hot reload message

### ISSUE THREAD

**Issue by 012e** [livebud/bud#60]
Changing a single line of code while running `bud run` generate 4 lines of  `Ready on localhost:3000` but not much useful information.
Is it supposed to work like that or something?

What about mimicking vite's?
![image](https://user-images.githubusercontent.com/98327371/168628662-795536e7-fe88-4ba1-bf49-b2d935e8e88c.png)

**Comment by matthewmueller** [comment]
It's currently working as expected, but I agree that the messaging & error handling needs another iteration. I also like Vite's messaging. The (x2, x3, etc) is super cool! Contributions welcome!

**Comment by matthewmueller** [comment]
Closed by #131
