### ISSUE TITLE
Error with NPM When Running make install During Contribution Set-Up

### ISSUE THREAD

**Issue by syke99** [livebud/bud#79]
I've been extremely impressed by and interested in but (great work @matthewmueller!!) and I wanted to begin contributing to an interesting bug that I saw in the issues. So I cloned bud and was following the instructions in [Contributing.md](https://github.com/livebud/bud/blob/main/Contributing.md), but I ran into an error when running make install.

OS: Windows 10
Go Version: 1.18.2
Node.js Version: 16.14.0

![Bud_Make_NPM_Error](https://user-images.githubusercontent.com/95064125/169695751-799605c5-768d-4345-89e0-ab82e58c509f.png)

**Comment by matthewmueller** [comment]
Thanks for the kind words Quinn! Does running `npm` standalone work for you? 

I'm not a windows user, so there's a good chance I'm doing something wrong. That would be something that would be super helpful to contribute! 😇

**Comment by syke99** [comment]
You're super welcome!! Keep up the great work!! And yes, running `npm` works as expected. I also updated npm itself to 8.10.0, but I'm still getting that error 😢

**Comment by syke99** [comment]
Ahh yeah, I forgot about that. Thanks @012e. That's most likely the issue @matthewmueller

**Comment by syke99** [comment]
@012e yeah, let me give that a shot!

**Comment by syke99** [comment]
Yeah, I used Chocolatey to download and install `make` on Windows. So that's probably the issue. I also saw in the Makefile that v8go isn't supported yet, so that will be an issue. But I'm still pressing forward because I'm going to compile a list of changes that will be needed to support Windows development, (some of which can already be made and *shouldn't* break anything and I can test that through one of my WSL2 setups) and then submit them individually as either issues (if they can already be implemented), suggestions for future improvements (such as implementing whatever else is needed once v8go support is added to Windows), or PRs for additions to the README for Windows development, such as the need for the gcc compiler.

**Comment by matthewmueller** [comment]
Accepting PRs! One reason I used `(cd livebud && npm install)` was to make sure the next command isn't inside `livebud/`, is there a way to do that in a Makefile on Windows? Otherwise we can do `cd ..` after.

**Comment by syke99** [comment]
I made one small change in `package/socket/child.go` that's specific to Windows development that's ready to be merged in. But should I create another branch, or do you want me to fork bud and submit a PR that way? (Something that should probably be added to [Contributing.md](https://github.com/livebud/bud/blob/main/Contributing.md) 😉 )

Also, I'm not sure about if there's a way to do that in a Makefile as I'm not very experienced with them at all. I can definitely spend some time researching that!!

 I've also got a small list of steps for setting up the gcc compiler for Windows, but I'm not sure how you wanted that addition (to the README or making another markdown file?) to be added since Windows development wont be possible until support for v8go is a thing.

**Comment by syke99** [comment]
Also, it looks like Windows support of v8go is [completed](https://github.com/rogchap/v8go/issues/7#issuecomment-746666956) @matthewmueller could you possibly enlighten me on what v8go is and how's it's being implemented? I see that it's looking for, but not finding, `-lv8`. But I haven't looked through the source code enough to see where this is being implemented, so thought maybe you'd have a good idea of what the issue may be 😅

**Comment by syke99** [comment]
I've opened [this](https://github.com/livebud/bud/pull/80) PR for this issue. I'll make a discussion about Windows development support to discuss the other issues 😋

**Comment by syke99** [comment]
> Chocolatey's `make` is kinda

Yeah, I got MinGW’s make to work and it’s added to my list of steps for setting up Windows development that I’m gonna but in a markdown file and put up a PR for whenever my other PR gets approved so I can make another fork

**Comment by 012e** [comment]
Uh, @syke99 you can just make a branch to push changes, doesn't need to be main.

**Comment by matthewmueller** [comment]
Closing in favor of the Window discussion
